/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 03-Dec-2019 10:51:48
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 41
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int filtr_length = 41;
const real32_T filtr[41] = {
  -0.002877596533,-0.0009176660678, 0.001807571622, 0.005103645846, 0.005902484525,
   0.001907182392,-0.005756559782, -0.01194744091, -0.01041707117,  0.00102267426,
    0.01681048796,  0.02520269342,  0.01568631083, -0.01179571263, -0.04246641323,
   -0.05191151798, -0.01960758865,  0.05671798065,   0.1553556621,   0.2385949641,
      0.271125406,   0.2385949641,   0.1553556621,  0.05671798065, -0.01960758865,
   -0.05191151798, -0.04246641323, -0.01179571263,  0.01568631083,  0.02520269342,
    0.01681048796,  0.00102267426, -0.01041707117, -0.01194744091,-0.005756559782,
   0.001907182392, 0.005902484525, 0.005103645846, 0.001807571622,-0.0009176660678,
  -0.002877596533
};
